game/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('fbase',views.fbase,name='fbase'),
    path('waiting',views.waiting,name="waiting"),
    path('showQuiz',views.showQuiz,name='showQuiz'),
    path('leaderboard',views.leaderboard,name='leaderboard'),
    path('download/<str:game>',views.download,name="download"),
    path('removed',views.removed,name="removed")
]

host/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('dashboard/',views.dashboard,name='dashboard'),
    path('quiz',views.quiz,name='quiz'),
    path('createQuiz',views.createQuiz,name='createQuiz'),
    path('done',views.done,name='done'),
    path('stats/<int:pk>',views.stats,name="stats"),
    path('quizPage/<int:pk>',views.quizPage,name='quizPage'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import serve
from django.conf import settings
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('login.urls')),
    path('',include('player.urls')),
    path('',include('host.urls')),
    path('',include('game.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root':settings.STATIC_ROOT}), 
]

host/models.py
from django.db import models
# Create your models here.

class Quiz(models.Model):
    hostname=models.CharField(max_length=15)
    quizId=models.IntegerField()
    questionNumber=models.IntegerField()
    question=models.CharField(max_length=500)
    option1=models.CharField(max_length=100)
    option2=models.CharField(max_length=100)
    option3=models.CharField(max_length=100)
    option4=models.CharField(max_length=100)
    answer=models.CharField(max_length=5)
    marks=models.IntegerField()
    timer=models.IntegerField()


# For storing the result records of student
class Record(models.Model):
  gameId=models.CharField(max_length=10)
  quizId=models.IntegerField()
  marks=models.TextField()
  playername=models.CharField(max_length=50)

# To handle many occurences of same quiz
class Game(models.Model):
  hostname=models.CharField(max_length=100)
  quizId=models.IntegerField()
  gameId=models.TextField()
  gameTime=models.TextField()

  # gameTime=ArrayField(models.DateTimeField(),default=list)

host/forms.py
from django import forms
from .models import Quiz

class createQuizForm(forms.ModelForm):
  CHOICES=(('1','1'),('2','2'),('3','3'),('4','4'))
  
  
  question=forms.CharField(max_length=500)
  option1=forms.CharField(max_length=100)
  option2=forms.CharField(max_length=100)
  option3=forms.CharField(max_length=100)
  option4=forms.CharField(max_length=100)
  answer=forms.ChoiceField(choices = CHOICES)
  marks=forms.IntegerField()
  timer=forms.IntegerField()
  class Meta:
    model = Quiz
    fields=['question','option1','option2','option3','option4','answer','marks','timer']

host/views.py
from django.shortcuts import render, redirect
from django.core import serializers
from player.models import Player
from .forms import createQuizForm
from .models import Quiz, Game, Record
from django.http import HttpResponse, Http404
import json
import shortuuid
import firebase_admin
from firebase_admin import db, credentials
import datetime,pytz
import time
from io import BytesIO
import pandas as pd
from django.contrib import messages

# mihir firebase
firebaseConfig = {
  "apiKey": "AIzaSyDNn1-wkMm-g0cH2BKQ6XjdLTl6ldds8ZE",
  "authDomain": "quizck-74e04.firebaseapp.com",
  "projectId": "quizck-74e04",
  "storageBucket": "quizck-74e04.appspot.com",
  "messagingSenderId": "555502389734",
  "appId": "1:555502389734:web:2a977e89e54df3c69cae27",
  "measurementId": "G-XFLZV89Q56",
  "databaseURL": "https://quizck-74e04-default-rtdb.firebaseio.com/"
}

import firebase_admin
import os
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="host/templates/firebase.json"

cred=credentials.Certificate('host/templates/firebase.json')
fireapp=firebase_admin.initialize_app(cred,{
  "databaseURL":"https://quizck-74e04-default-rtdb.firebaseio.com/"
},name="host")
dbRef = db.reference()


def dashboard(req):
  username=""
  quiz=""
  try:
    username = req.session['username']
    quiz = Quiz.objects.filter(hostname=username).values_list('quizId', flat=True).distinct()
  except:
    raise Http404
      
  quizzes = []
  i = 1
  for x in quiz:
      quizzes.append([i, x])
      i += 1
  return render(req, 'dashboard.html', {'quizzes': quizzes})


def quiz(req):
  username=""
  temp=""
  try:
    username = req.session['username']
    temp = Quiz.objects.filter(hostname=username).values_list('quizId',flat=True)
  except:
    raise Http404
  mx = 0
  for x in temp:
    mx = max(mx, x)
  req.session['quizId'] = mx + 1
  return redirect('createQuiz')


def createQuiz(req):
    if req.method == 'POST':
        form = createQuizForm(req.POST)
        if form.is_valid():
          cnt=""
          try:
            cnt=Quiz.objects.filter(quizId=req.session['quizId'],hostname=req.session['username']).count()
          except:
            raise Http404
          questionNumber = cnt+1
          question = req.POST['question']
          option1 = req.POST['option1']
          option2 = req.POST['option2']
          option3 = req.POST['option3']
          option4 = req.POST['option4']
          answer = req.POST['answer']
          marks = req.POST['marks']
          timer = req.POST['timer']

          username = req.session['username']
          quizId = req.session['quizId']

          quiz = Quiz(hostname=username,
                      quizId=quizId,
                      questionNumber=questionNumber,
                      question=question,
                      option1=option1,
                      option2=option2,
                      option3=option3,
                      option4=option4,
                      answer=answer,
                      marks=marks,
                      timer=timer)

          quiz.save()
          form = createQuizForm()
    else:
        form = createQuizForm()

    return render(req, 'createQuiz.html', {'form': form})


def done(req):
    if req.method == 'POST':
      form = createQuizForm(req.POST)
      if form.is_valid():
        cnt=''
        try:
          cnt=Quiz.objects.filter(quizId=req.session['quizId'],hostname=req.session['username']).count()
        except:
          raise Http404
        questionNumber = cnt+1
        question = req.POST['question']
        option1 = req.POST['option1']
        option2 = req.POST['option2']
        option3 = req.POST['option3']
        option4 = req.POST['option4']
        answer = req.POST['answer']
        marks = req.POST['marks']
        timer = req.POST['timer']

        username = req.session['username']
        quizId = req.session['quizId']

        quiz = Quiz(hostname=username,quizId=quizId,questionNumber=questionNumber,question=question,option1=option1,option2=option2,option3=option3,option4=option4,answer=answer,marks=marks,timer=timer)

        quiz.save()

    return redirect('dashboard')
    
def stats(req, **primarykey):
  quizId=primarykey['pk']
  game=""
  hostname=""
  try:
    hostname=req.session['username']
    game=list(Game.objects.filter(hostname=hostname,quizId=quizId))
  except:
    raise Http404
  if not game:
    return render(req,'stats.html',{"quizId":quizId,"games":[]})
  game=game[0]
  gameIds=game.gameId.split(",")
  gameTimes=game.gameTime.split(",")
  games=[]
  for i in range(len(gameIds)):
    games.append([gameIds[i],gameTimes[i]])

  games.sort(key = lambda x: x[1])
  games.reverse()
  return render(req,'stats.html',{"games":games,"quizId":quizId})

def quizPage(req, **primarykey):
    quizId = primarykey['pk']
    qz=""
    try:
      qz = Quiz.objects.filter(quizId=quizId, hostname=req.session["username"])
    except:
      raise Http404
    qz = serializers.serialize('json', qz)
    qz = json.loads(qz)
    code = shortuuid.ShortUUID().random(length=4)
    req.session["code"] = code
    req.session['user']="admin"
    req.session['quizId']=quizId
    
    game=""
    dt=""
    quizId=""
    username=""
    try:
      username = req.session['username']
      quizId = req.session['quizId']
      dt=datetime.datetime.now(pytz.timezone('Asia/Kolkata'))
      
      game=list(Game.objects.filter(hostname=username,quizId=quizId))
    except:
      raise Http404

    if len(game)==0:
      game=Game(hostname=username,quizId=quizId,gameId=code,gameTime=dt.strftime("%b %d %Y %H:%M:%S"))
      game.save()
    else:
      game=game[0]
      gameId=game.gameId.split(",")
      gameTime=game.gameTime.split(",")
      gameId.append(code)
      gameTime.append(dt.strftime("%b %d %Y %H:%M:%S"))
      game.gameId=",".join(gameId)
      game.gameTime=",".join(gameTime)
      game.save()

    dbRef.child("games").child(code).set({
      'host': req.session["username"],
      'next': 0,
      'newplayer': [''],
      'started':0
    })
    return redirect('waiting')

def logout(req):
  for key in list(req.session.keys()):
    if not key.startswith("_"):
      del req.session[key]

  return redirect('login')

host/templates/base.html
<html>
  <head>
      {% block extra %}
      {% endblock %}
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
      <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" integrity="sha512-8bHTC73gkZ7rZ7vpqUQThUDhqcNFyYi2xgDgPDHc+GXVGHXq+xPjynxIopALmOPqzo9JZj0k6OqqewdGO3EsrQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js" integrity="sha512-dqw6X88iGgZlTsONxZK9ePmJEFrmHwpuMrsUChjAw1mRUhUITE5QU9pkcSox+ynfLhL15Sv2al5A0LVyDCmtUw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
      
          
    <style type="text/css">
      {% block style %}
      {% endblock %}
    </style>
  </head>
  <body>
    {% block body %}
    {% endblock %}
  </body>
</html>

host/templates/createQuiz.html
{% extends "base.html" %}
{% load static %}
{% block style %}
@media only screen and (max-width: 200px) {
      .masthead.segment {
        min-height: 50px;
      }
      .masthead h1.ui.header {
        font-size: 2em;
        margin-top: 1.5em;
      }
      .masthead h2 {
        margin-top: 0.5em;
        font-size: 1.5em;
      }
    }
    .masthead.segment {
      min-height: 50px;
      padding: 1em 0em;      
    }
    .masthead h1.ui.header {
      margin-bottom: 0em;
      font-size: 5em;
      font-weight: normal;
    }
    .masthead h2 {
      font-size: 2em;
      font-weight: normal;
      margin-bottom: 0em;
    }
    body {
      background-color: #DADADA;
      font-family:'Times New Roman';
    }
    body > .grid {
      height: 100%;
    }
    .ui.list{
      height: 200px;
      overflow-y: scroll;
    }
    .ui.menu{
      height: 80px;
    }
    .ui.form{
      margin-top: 4em;
      /* margin-left: 4em; */
    }
    .field{
      width: 20em;
    }
    .outer{
      background-color:red;
      width:100%;
    }
    .ui.large.form {
      font-size: 1.5em;
    }
    .container{
      text-align: center;
    }
    .hidden_button{
      visibility:hidden;
    }
    .split {
      height: 100%;
      width: 50%;
      position: fixed;
      z-index: 1;
      top: 0;
      overflow-x: hidden;
    }
    .left {
      left: 0;
    }
    .inner {
      right: 0;
    }
    .ui.grid{
      margin-top:0px;
    }
    input{
      border-radius:0.5em !important;
    }
{% endblock %}
{% block body %}
  <div class="ui grid">
    <div class="ui seven wide column inverted vertical masthead center aligned segment">
      
      <h1 class="ui inverted header" style="margin-top:2em; margin-bottom:1em;">Create Quiz</h1><br>
      <img class="ui centered big image" src="{% static 'book.svg' %}">
    </div>

    <div class="ui nine wide column" style="margin-top:100px;">
      <form class="ui large form" action="" method="POST">
        {% csrf_token %}
        <div class="ui grid">
          <div class="three wide column"></div>
          <div class="ten wide field">
            <label>Enter Question</label>
            <input id="id_question" type="text" name="question" placeholder="Enter Question">
          </div>
          <div class="three wide column"></div>
          <div class="three wide column"></div>
          <div class="ten wide field">
            <div class="two fields">
              <div class="eight wide field">
                <label class="">Option1</label>
                <input id="id_option1" type="text" name="option1" placeholder="">
              </div>
              <div class="eight wide field">
                <label>Option2</label>
                <input id="id_option2" type="text" name="option2" placeholder="">
              </div>
            </div>
          </div>
          <div class="three wide column"></div>
          <div class="three wide column"></div>
          <div class="ten wide field">
            <div class="two fields">
              <div class="eight wide field">
                <label class="">Option3</label>
                <input id="id_option3" type="text" name="option3" placeholder="">
              </div>
              <div class="eight wide field">
                <label>Option4</label>
                <input id="id_option4" type="text" name="option4" placeholder="">
              </div>
            </div>
          </div>
          <div class="three wide column"></div>
          <div class="three wide column"></div>
          <div class="ten wide field">
            <div class="three fields">
              <div class="eight wide field">
                <label>Answer</label>
                <div class="ui selection dropdown">
                  <input type="hidden" name="answer" id="id_answer">
                  <i class="dropdown icon"></i>
                  <div class="default text">Select Answer</div>
                  <div class="menu">
                    <div class="item" data-value="1">Option1</div>
                    <div class="item" data-value="2">Option2</div>
                    <div class="item" data-value="3">Option3</div>
                    <div class="item" data-value="4">Option4</div>
                  </div>
                </div>
              </div>
              <div class="one wide field"></div>
              <div class="three wide field">
                <label>Marks</label>
                <input id="id_marks" type="number" name="marks">
              </div>
              <div class="one wide field"></div>
              <div class="three wide field">
                <label>Time(s)</label>
                <input id="id_timer" type="text" name="timer">
              </div>

            </div>
          </div>
          <div class="three wide column"></div>
          
          <div class="six wide column"></div>
          <div class="container" style="margin-top:120px;">
            <div class="center-button">
              <div class="massive ui buttons">
                <a class="ui animated positive button" tabindex="0" id="next">
                  <div class="visible content">Next</div>
                  <div class="hidden content">
                    <i class="right arrow icon"></i>
                  </div>
                </a>
                <div class="or"></div>
                <div class="ui animated button" tabindex="0" id="done">
                  <div class="visible content">Done</div>
                  <div class="hidden content">
                    <i class="check icon"></i>
                  </div>
                </div>


                <!-- <button type="submit" class="ui positive button" formaction="done">Done</button> -->
              </div>
            </div>
          </div>
        </div>
        <input type="submit" formaction="createQuiz" class="hidden_button" id="hidden_next"/>
        <input type="submit" formaction="done" class="hidden_button" id="hidden_done"/>
      </form>
    </div>
  </div>
  <script>
    $('.ui.dropdown').dropdown();
    $('#next').click(function(){
      $("#hidden_next").click();
    });
    $('#done').click(function(){
      $("#hidden_done").click();
    });
  </script>
{% endblock %}

host/templates/dashboard.html
{% load static %}
<html>
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" integrity="sha512-8bHTC73gkZ7rZ7vpqUQThUDhqcNFyYi2xgDgPDHc+GXVGHXq+xPjynxIopALmOPqzo9JZj0k6OqqewdGO3EsrQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js" integrity="sha512-dqw6X88iGgZlTsONxZK9ePmJEFrmHwpuMrsUChjAw1mRUhUITE5QU9pkcSox+ynfLhL15Sv2al5A0LVyDCmtUw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <style>
      body {
        background-color: #616161
      }
      label.btn {
          padding: 18px 60px;
          white-space: normal;
          -webkit-transform: scale(1.0);
          -moz-transform: scale(1.0);
          -o-transform: scale(1.0);
          -webkit-transition-duration: .3s;
          -moz-transition-duration: .3s;
          -o-transition-duration: .3s
      }
      label.btn:hover {
          text-shadow: 0 3px 2px rgba(0, 0, 0, 0.4);
          -webkit-transform: scale(1.1);
          -moz-transform: scale(1.1);
          -o-transform: scale(1.1);
      }
      label.btn-block {
          text-align: left;
          position: relative
      }
      label .btn-label {
          position: absolute;
          left: 0;
          top: 0;
          display: inline-block;
          padding: 0 10px;
          background: #000000;
          height: 100%
      }

      label .glyphicon {
          top: 34%
      }
      ::-webkit-scrollbar {
        width: 0;
        background: transparent;
      }

      .element-animation1 {
          animation: animationFrames ease .8s;
          animation-iteration-count: 1;
          transform-origin: 50% 50%;
          -webkit-animation: animationFrames ease .8s;
          -webkit-animation-iteration-count: 1;
          -webkit-transform-origin: 50% 50%;
          -ms-animation: animationFrames ease .8s;
          -ms-animation-iteration-count: 1;
          -ms-transform-origin: 50% 50%
      }

      .element-animation2 {
          animation: animationFrames ease 1s;
          animation-iteration-count: 1;
          transform-origin: 50% 50%;
          -webkit-animation: animationFrames ease 1s;
          -webkit-animation-iteration-count: 1;
          -webkit-transform-origin: 50% 50%;
          -ms-animation: animationFrames ease 1s;
          -ms-animation-iteration-count: 1;
          -ms-transform-origin: 50% 50%
      }

      .element-animation3 {
          animation: animationFrames ease 1.2s;
          animation-iteration-count: 1;
          transform-origin: 50% 50%;
          -webkit-animation: animationFrames ease 1.2s;
          -webkit-animation-iteration-count: 1;
          -webkit-transform-origin: 50% 50%;
          -ms-animation: animationFrames ease 1.2s;
          -ms-animation-iteration-count: 1;
          -ms-transform-origin: 50% 50%
      }

      .element-animation4 {
          animation: animationFrames ease 1.4s;
          animation-iteration-count: 1;
          transform-origin: 50% 50%;
          -webkit-animation: animationFrames ease 1.4s;
          -webkit-animation-iteration-count: 1;
          -webkit-transform-origin: 50% 50%;
          -ms-animation: animationFrames ease 1.4s;
          -ms-animation-iteration-count: 1;
          -ms-transform-origin: 50% 50%
      }

      @keyframes animationFrames {
          0% {
              opacity: 0;
              transform: translate(-1500px, 0px)
          }

          60% {
              opacity: 1;
              transform: translate(30px, 0px)
          }

          80% {
              transform: translate(-10px, 0px)
          }

          100% {
              opacity: 1;
              transform: translate(0px, 0px)
          }
      }

      @-webkit-keyframes animationFrames {
          0% {
              opacity: 0;
              -webkit-transform: translate(-1500px, 0px)
          }

          60% {
              opacity: 1;
              -webkit-transform: translate(30px, 0px)
          }

          80% {
              -webkit-transform: translate(-10px, 0px)
          }

          100% {
              opacity: 1;
              -webkit-transform: translate(0px, 0px)
          }
      }
      .masthead h1.ui.header {
      margin-bottom: 0em;
      font-size: 5em;
      font-weight: normal;
    }

      .modal-header {
          background-color: transparent;
          color: inherit
      }

      .modal-body {
          min-height: 300px;
          max-height: 65%;
          overflow-y:scroll;
          overflow-x:hidden;
      }
      .btn-danger{
        background-color: teal;
        border-color: white;
      }
      .btn-danger:hover{
        background-color:orange;
      }
      .ui.grid{
      margin-top:0px;
    }
    body > .grid {
      height: 100%;
    }
    </style>
  </head>

  <body>
    <div class="ui grid">
      <div class="ui seven wide column inverted vertical masthead center aligned segment" style="height:100%">
        
        <h1 class="ui inverted header" style="margin-top:2em; margin-bottom:1em;">Dashboard</h1><br>
        <img class="ui centered big image" src="{% static 'dashboard.svg' %}">
      </div>

      <div class="ui nine wide column"> 
        <div class="ui container">
          <div class="ui large secondary pointing menu" style="border-width:0px;">
            <div class="right item">
              <a href="{% url 'login' %}" class="ui inverted button">Logout</a>
            </div>
            
          </div>
        </div>   
        <center style="margin-top:20px;">
        <form id="form" action="../quiz" method="POST">
          {% csrf_token %}
          <button type="submit" class="ui teal large button" id="create">
            <i class="plus icon"></i>
            Create Quiz
          </button>
        </form>
        </center>
        <div class="container-fluid">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                    <center><h3>Select Quiz</h3></center>
                </div>
                <div class="modal-body">
                  <div class="col-xs-3 5"> </div>
                  <div class="quiz" id="quiz" data-toggle="buttons">
                    {% for quiz1,quiz2 in quizzes %}
                      <label onclick="quiz('{{quiz2}}')" class="element-animation1 btn btn-lg btn-danger btn-block">
                        <span class="btn-label"><i class="glyphicon glyphicon-chevron-right"></i></span>
                        {{ quiz1 }}
                      </label>
                    {% endfor %}
                  </div>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </body>

  <script>
    function quiz(id){
        window.location = "{% url 'stats' 1234 %}".replace(/1234/, id.toString());
    }
    $('#create').click(function(){
      $("#create").addClass("loading");
    });
  </script>
</html>

host/templates/quizPage.html
<html>
    <head>
        <title>JavaScript</title> 
    </head>
    <body>
      <form action="../tryy" method="POST">
        {% csrf_token %}
        {% for q in query %}
        <br>
        Question{{q.fields.questionNumber}}:&nbsp
        {{q.fields.question}}<br>
        1)<input type="radio" id="option1" value="1" name="options">
          <label for="html">{{q.fields.option1}}</label><br>
        2)<input type="radio" id="option2" value="2" name="options">
          <label for="html">{{q.fields.option2}}</label><br>
        3)<input type="radio" id="option3" value="3" name="options">
          <label for="html">{{q.fields.option3}}</label><br>
        4)<input type="radio" id="option4" value="4" name="options">
          <label for="html">{{q.fields.option4}}</label><br>
        Marks:{{q.fields.marks}}<br>
        Time:{{q.fields.timer}}
        <br><hr>
        {% endfor %}
        <input type="submit" value="Done">
      </form>
      <br>
      {{code}}
      <div id="stopwatch">       
      </div>
      <button onclick="timerCycle()">Click</button>
      <button onclick="play()">Play</button>
    </body>
</html>

<script>
  var sec = {{sec}};
  const timer = document.getElementById('stopwatch');
  function timerCycle() {

      sec=sec-1;
      if(sec<0) return;
      var x=sec;
      if (x < 10 || x == 0) {
        x='0'+x;
      }
      timer.innerHTML = x;
      if(sec!=0) setTimeout("timerCycle()", 1000);
  }
  function play(){
    window.location="{% url 'waiting' %}";
  }
  
</script>

host/templates/stats.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
@media only screen and (max-width: 200px) {
      .masthead.segment {
        min-height: 150px;
      }
      .masthead h1.ui.header {
        font-size: 2em;
        margin-top: 1.5em;
      }
      .masthead h2 {
        margin-top: 0.5em;
        font-size: 1.5em;
      }
    }
    .masthead.segment {
      min-height: 50px;
      padding: 1em 0em;      
    }
    .masthead h1.ui.header {
      margin-top: 0.2em;
      margin-bottom: 0em;
      font-size: 5em;
      font-weight: normal;
    }
    .masthead h2 {
      font-size: 2em;
      font-weight: normal;
      margin-bottom: 2em;
    }
    #head{
      margin-bottom:1.5em;
    }
    body {
      background-color: #DADADA;
      font-family:'Times New Roman';
    }
    body > .grid {
      height: 100%;
    }
    .ui.list{
      height: 200px;
      overflow-y: scroll;
    }
    .ui.menu{
      height: 80px;
    }
    #playQ{
      margin-top:0.5em;
    }
    #result{
      height: 45%;
      overflow-y:scroll;
    }
{% endblock %}
{% block body %}
<div id="head" class="ui inverted vertical masthead center aligned segment ">
    <div class="ui text container">      
      <h1 class="ui inverted header">Statistics</h1><br>
      <div class="ui two colum centered grid">
        <img class="large ui image" src="{% static 'files.svg' %}">        
      </div>
      <br>
    </div>
    <a id="playQ" onclick="quiz('{{quizId}}')" class="ui huge primary button">
      Play Quiz <i class="right arrow icon"></i>
      </a>
  </div>
<div class="ui container" id="result">
  <table class="ui celled table">
    <thead>
      <tr>
        <th>Sr. No</th>
        <th>Quiz Date</th>
        <th>Quiz Code</th>
        <th> </th>
      </tr>
    </thead>
    <tbody>
      {% for gameId , gameTime in games %}
        <tr>
          <td>{{forloop.counter}}</td>
          <td>{{gameTime}}</td>
          <td>{{gameId}} </td>
          <td><button class="ui teal button" onclick="download('{{gameId}},{{quizId}}')">
            Download Result&nbsp;
            <i class="download icon"></i>
            </button><br></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
  <script>
    function quiz(id){
        window.location = "{% url 'quizPage' 1234 %}".replace(/1234/, id.toString());
    }
    function download(id){
        window.location = "{% url 'download' 1234 %}".replace(/1234/, id.toString());
    }
</script>
{% endblock %}